import SectionHeader from "./SectionHeader";

const skillCategories = [
    {
        category: "Frontend",
        skills: [
            { name: "HTML", filename: "HTML.svg" },
            { name: "CSS", filename: "CSS.svg" },
            { name: "Javascript", filename: "Javascript.svg" },
            { name: "Tailwind CSS", filename: "Tailwind-CSS.svg" },
            { name: "React", filename: "React.svg" },
            { name: "Vite", filename: "Vite.svg" },
        ],
    },
    {
        category: "Backend",
        skills: [
            { name: "Python", filename: "Python.svg" },
            { name: "C++", filename: "C-plus-plus.svg" },
            { name: "Golang", filename: "Golang.svg" },
            { name: "Fiber", filename: "Fiber.png" },
            { name: "PHP", filename: "PHP.svg" },
            { name: "MySQL", filename: "MySQL.svg" },
        ],
    },
    {
        category: "Miscellaneous",
        skills: [
            { name: "Git", filename: "Git.svg" },
            { name: "Docker", filename: "Docker.svg" },
            { name: "AWS", filename: "AWS.png" },
            { name: "Ubuntu", filename: "Ubuntu.svg" },
            { name: "RHEL", filename: "RHEL.svg" },
        ],
    },
];

function Skills() {
    return (
        <section id="Skills" className="p-8 pt-24 mx-auto">
            <SectionHeader title="Skills" />

            {/* Outer wrapper that uses flex to align the entire skills container center while decreasing its width */}
            <div className="flex items-center justify-center">
                {/* Main container for skill icon cards (Content will be generated by Javascript) */}
                <div className="flex flex-col items-left space-y-12 w-5/6">
                    {skillCategories.map(function (category, category_index) {
                        return (
                            <div
                                key={category_index}
                                className="flex flex-col items-center space-y-8 w-full"
                            >
                                <h3 className="text-white/90 text-3xl font-jetbrains font-medium">
                                    {category.category}
                                </h3>
                                <div className="flex flex-wrap items-center justify-center gap-x-8 gap-y-8">
                                    {category.skills.map(function (
                                        skill,
                                        skill_index
                                    ) {
                                        return (
                                            <article
                                                key={skill_index}
                                                className="flex flex-col items-center space-y-4"
                                            >
                                                <div className="card-border-gradient rounded-xl transition-transform duration-180 hover:scale-115">
                                                    <div className="bg-gray-800 text-white rounded-xl p-3 w-auto">
                                                        <img
                                                            src={`/${skill.filename}`}
                                                            alt={skill.name}
                                                            className="h-[5em] w-[5em]"
                                                        />
                                                    </div>
                                                </div>
                                                <p className="font-jetbrains text-gray-300 text-md opacity-80">
                                                    {skill.name}
                                                </p>
                                            </article>
                                        );
                                    })}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </section>
    );
}

export default Skills;
